name: OpToggle
version: 1.0
main: org.simondoestuff.optoggle.OPToggle
author: simondoestuff
api-version: 1.16
commands:
  OPToggle:
    aliases:
      - "opt"
    usage: "/opt"
    description: "Toggle op anytime. Must be super-oped."
  SuperOP:
    aliases: "sop"
    usage: "/sop <player>"
    description: "List all super-ops or use console to toggle a super-op."
